name: Dokkan Asset Updater

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-assets:
    runs-on: windows-latest

    steps:
      - name: Checkout Backend Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.11'  # Change this to your required Python version
      
      - name: Save settings.json state before running Dokkan_Asset_Downloader
        id: before_state
        run: |
          if (Test-Path "Dokkan_Asset_Downloader\settings.json") {
            $settings = Get-Content -Raw -Path "Dokkan_Asset_Downloader\settings.json" | ConvertFrom-Json
            $glbAssetVersion = $settings.GlbAssetVersion
          } else {
            $glbAssetVersion = "no_file"
          }
          echo "glbAssetVersion=$glbAssetVersion" >> $env:GITHUB_OUTPUT
        shell: pwsh

      - name: Run Dokkan_Asset_Downloader
        run: |
          cd "Dokkan_Asset_Downloader"  || exit /b 1
          (
            echo 1
            echo.
          ) | Dokkan_Asset_Downloader_v2.5.2_WIN_x64.exe
        shell: cmd
      
      - name: Save settings.json state after running Dokkan_Asset_Downloader
        id: after_state
        run: |
          if ("${{ steps.before_state.outputs.glbAssetVersion }}" -ne "${{ steps.after_state.outputs.glbAssetVersion }}") {
            echo "changed=true" >> $env:GITHUB_OUTPUT
          } else {
            echo "changed=false" >> $env:GITHUB_OUTPUT
          }
        shell: pwsh

      - name: Check if settings.json has changed
        id: check_changes
        run: |
          if ("${{ steps.before_state.outputs.hash }}" -ne "${{ steps.after_state.outputs.hash }}") {
            echo "::set-output name=changed::true"
          } else {
            echo "::set-output name=changed::false"
          }
        shell: pwsh

      - name: Install Python Dependencies
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          pip install -r requirements.txt
        shell: cmd


      - name: Create Temp jsons Folder
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          mkdir temp_jsons
          mkdir temp_jsons\jsons
          mkdir temp_jsons\jsonsEZA
          mkdir temp_jsons\jsonsSEZA
          mkdir temp_jsons\uniqueJsons
          mkdir temp_jsons\uniqueJsons\unitBasics
        shell: cmd

      

      - name: Run Database and JSON Scripts
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          python Database_expander.py
          python dokkan_Json_creator.py
          python uniqueJsonCreator.py
        shell: cmd

      - name: Checkout Frontend Repository
        if: steps.check_changes.outputs.changed == 'true'
        uses: actions/checkout@v3
        with:
          repository: Niccccccccccccc/dokkan-frontend
          token: ${{ secrets.FRONTEND_REPO_PAT }}
          path: frontend

      - name: Copy Updated DDL Files to Frontend
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          xcopy /E /Y "Dokkan_Asset_Downloader\temp_downloads" "frontend\dbManagement\DokkanFiles"
        shell: cmd

      - name: Copy Updated JSON Files to Frontend
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          xcopy /E /Y "temp_jsons" "frontend\dbManagement"
        shell: cmd

      - name: Commit and Push Changes to Frontend
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          cd frontend
          git config --global user.email "horvat.nicholas@gmail.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Automated update of Dokkan assets" || echo "No changes to commit"
          git push
        shell: cmd

      - name: Checkout Backend Repository
        if: steps.check_changes.outputs.changed == 'true'
        uses: actions/checkout@v3
        with:
          repository: Niccccccccccccc/dokkan-backend
          token: ${{ secrets.BACKEND_REPO_PAT }}
          path: backend
      

      - name: Copy Updated backend Files to Backend
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          xcopy /E /Y "Dokkan_Asset_Downloader\settings.json" "backend\Dokkan_Asset_Downloader\settings.json"
          xcopy /E /Y "dataGB" "backend\dataGB"
        shell: cmd
      
      - name: Commit and Push Updated Settings & CSVs
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          cd backend
          git config --global user.email "horvat.nicholas@gmail.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Automated update of Dokkan assets" || echo "No changes to commit"
          git push
        shell: cmd