name: Dokkan Asset Updater

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-assets:
    runs-on: windows-latest

    steps:
      - name: Checkout Backend Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.11'  # Change this to your required Python version
      
      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt
        shell: cmd

      - name: Create Temp Download Folder
        run: mkdir Dokkan_Asset_Downloader\temp_downloads
        shell: cmd

      - name: Create Temp jsons Folder
        run: |
          mkdir temp_jsons
          mkdir temp_jsons\jsons
          mkdir temp_jsons\jsonsEZA
          mkdir temp_jsons\jsonsSEZA
          mkdir temp_jsons\uniqueJsons
          mkdir temp_jsons\uniqueJsons\unitBasics
        shell: cmd

      - name: Run Dokkan_Asset_Downloader
        run: |
          cd "Dokkan_Asset_Downloader"  || exit /b 1
          (
            echo 1
            echo.
          ) | Dokkan_Asset_Downloader_v2.5.2_WIN_x64.exe
        shell: cmd

      - name: Run Database and JSON Scripts
        run: |
          python Database_expander.py
          python dokkan_Json_creator.py
          python uniqueJsonCreator.py
        shell: cmd

      - name: Checkout Frontend Repository
        uses: actions/checkout@v3
        with:
          repository: Niccccccccccccc/dokkan-frontend
          token: ${{ secrets.FRONTEND_REPO_PAT }}
          path: frontend

      - name: Copy Updated DDL Files to Frontend
        run: |
          xcopy /E /Y "Dokkan_Asset_Downloader\temp_downloads" "frontend\dbManagement\DokkanFiles"
        shell: cmd

      - name: Copy Updated JSON Files to Frontend
        run: |
          xcopy /E /Y "temp_jsons" "frontend\dbManagement"
        shell: cmd

      - name: Commit and Push Changes to Frontend
        run: |
          cd frontend
          git config --global user.email "horvat.nicholas@gmail.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Automated update of Dokkan assets" || echo "No changes to commit"
          git push
        shell: cmd

      - name: Commit and Push Updated Settings & CSVs
        env:
          GH_TOKEN: ${{ secrets.FRONTEND_REPO_PAT }}
        run: |
          git config --global user.email "horvat.nicholas@gmail.com"
          git config --global user.name "GitHub Actions"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/Niccccccccccccc/dokkan-backend.git
          git add "Dokkan_Asset_Downloader/settings.json"
          git add "*.csv"
          git commit -m "Automated update of Dokkan assets" || echo "No changes to commit"
          git push
        shell: cmd